// <auto-generated />
using System;
using LibroManager.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibroManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250301150202_AddUbicacionRelation")]
    partial class AddUbicacionRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibroManager.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            AutorId = 1,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            AutorId = 2,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "J.K. Rowling"
                        },
                        new
                        {
                            AutorId = 3,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Stephen King"
                        },
                        new
                        {
                            AutorId = 4,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Isabel Allende"
                        },
                        new
                        {
                            AutorId = 5,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Haruki Murakami"
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Novela"
                        },
                        new
                        {
                            CategoriaId = 2,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            CategoriaId = 3,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Terror"
                        },
                        new
                        {
                            CategoriaId = 4,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            CategoriaId = 5,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Historia"
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            Email = "ana.garcia@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana García"
                        },
                        new
                        {
                            EstudianteId = 2,
                            Email = "pedro.martinez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro Martínez"
                        },
                        new
                        {
                            EstudianteId = 3,
                            Email = "maria.lopez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María López"
                        },
                        new
                        {
                            EstudianteId = 4,
                            Email = "carlos.rodriguez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            EstudianteId = 5,
                            Email = "laura.fernandez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura Fernández"
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("LibroId");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.HasIndex("UbicacionId");

                    b.ToTable("Libros", t =>
                        {
                            t.HasCheckConstraint("CK_Libro_ISBN", "LEN([ISBN]) >= 10 AND LEN([ISBN]) <= 13");
                        });

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307474728",
                            Serial = "GAB-SOL-001",
                            Titulo = "Cien años de soledad",
                            UbicacionId = 1
                        },
                        new
                        {
                            LibroId = 2,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "ROW-HP1-001",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 5
                        },
                        new
                        {
                            LibroId = 3,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788497593793",
                            Serial = "KIN-RES-001",
                            Titulo = "El resplandor",
                            UbicacionId = 8
                        },
                        new
                        {
                            LibroId = 4,
                            AutorId = 4,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780525433477",
                            Serial = "ALL-ESP-001",
                            Titulo = "La casa de los espíritus",
                            UbicacionId = 2
                        },
                        new
                        {
                            LibroId = 5,
                            AutorId = 5,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788483835043",
                            Serial = "MUR-TOK-001",
                            Titulo = "Tokio blues",
                            UbicacionId = 3
                        },
                        new
                        {
                            LibroId = 6,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307387264",
                            Serial = "GAB-AMO-001",
                            Titulo = "El amor en los tiempos del cólera",
                            UbicacionId = 4
                        },
                        new
                        {
                            LibroId = 7,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884957",
                            Serial = "ROW-HP2-001",
                            Titulo = "Harry Potter y la cámara secreta",
                            UbicacionId = 6
                        },
                        new
                        {
                            LibroId = 8,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9781501142970",
                            Serial = "KIN-IT-001",
                            Titulo = "It",
                            UbicacionId = 9
                        },
                        new
                        {
                            LibroId = 9,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307474728",
                            Serial = "GAB-SOL-002",
                            Titulo = "Cien años de soledad",
                            UbicacionId = 10
                        },
                        new
                        {
                            LibroId = 10,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307474728",
                            Serial = "GAB-SOL-003",
                            Titulo = "Cien años de soledad",
                            UbicacionId = 11
                        },
                        new
                        {
                            LibroId = 11,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "ROW-HP1-002",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 12
                        },
                        new
                        {
                            LibroId = 12,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "ROW-HP1-003",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 13
                        },
                        new
                        {
                            LibroId = 13,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "ROW-HP1-004",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 5
                        },
                        new
                        {
                            LibroId = 14,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788497593793",
                            Serial = "KIN-RES-002",
                            Titulo = "El resplandor",
                            UbicacionId = 14
                        },
                        new
                        {
                            LibroId = 15,
                            AutorId = 4,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780525433477",
                            Serial = "ALL-ESP-002",
                            Titulo = "La casa de los espíritus",
                            UbicacionId = 15
                        },
                        new
                        {
                            LibroId = 16,
                            AutorId = 4,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780525433477",
                            Serial = "ALL-ESP-003",
                            Titulo = "La casa de los espíritus",
                            UbicacionId = 2
                        },
                        new
                        {
                            LibroId = 17,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884957",
                            Serial = "ROW-HP2-002",
                            Titulo = "Harry Potter y la cámara secreta",
                            UbicacionId = 6
                        },
                        new
                        {
                            LibroId = 18,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884957",
                            Serial = "ROW-HP2-003",
                            Titulo = "Harry Potter y la cámara secreta",
                            UbicacionId = 7
                        },
                        new
                        {
                            LibroId = 19,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9781501142970",
                            Serial = "KIN-IT-002",
                            Titulo = "It",
                            UbicacionId = 9
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("LibroId", "EstudianteId", "FechaPrestamo")
                        .IsUnique();

                    b.ToTable("Prestamos", t =>
                        {
                            t.HasCheckConstraint("CK_Prestamo_FechaVencimiento", "[FechaVencimiento] > [FechaPrestamo]");
                        });

                    b.HasData(
                        new
                        {
                            PrestamoId = 1,
                            Estado = 1,
                            EstudianteId = 1,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDevolucion = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 1
                        },
                        new
                        {
                            PrestamoId = 2,
                            Estado = 2,
                            EstudianteId = 2,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 2
                        },
                        new
                        {
                            PrestamoId = 3,
                            Estado = 1,
                            EstudianteId = 3,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDevolucion = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 3
                        },
                        new
                        {
                            PrestamoId = 4,
                            Estado = 0,
                            EstudianteId = 4,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 4
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionId"));

                    b.Property<string>("Estante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.HasKey("UbicacionId");

                    b.ToTable("Ubicaciones");

                    b.HasData(
                        new
                        {
                            UbicacionId = 1,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 2,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 3,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 4,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 5,
                            Estante = "B",
                            Nivel = 2,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 6,
                            Estante = "B",
                            Nivel = 2,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 7,
                            Estante = "B",
                            Nivel = 2,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 8,
                            Estante = "C",
                            Nivel = 3,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 9,
                            Estante = "C",
                            Nivel = 3,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 10,
                            Estante = "A",
                            Nivel = 2,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 11,
                            Estante = "A",
                            Nivel = 2,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 12,
                            Estante = "B",
                            Nivel = 1,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 13,
                            Estante = "B",
                            Nivel = 1,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 14,
                            Estante = "C",
                            Nivel = 1,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 15,
                            Estante = "C",
                            Nivel = 1,
                            Posicion = 2
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Libro", b =>
                {
                    b.HasOne("LibroManager.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibroManager.Models.Categoria", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibroManager.Models.Ubicacion", "Ubicacion")
                        .WithMany("Libros")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("LibroManager.Models.Prestamo", b =>
                {
                    b.HasOne("LibroManager.Models.Estudiante", "Estudiante")
                        .WithMany("Prestamos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibroManager.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("LibroManager.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("LibroManager.Models.Categoria", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("LibroManager.Models.Estudiante", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("LibroManager.Models.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("LibroManager.Models.Ubicacion", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
