// <auto-generated />
using System;
using LibroManager.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibroManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibroManager.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LibroManager.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            AutorId = 1,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            AutorId = 2,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "J.K. Rowling"
                        },
                        new
                        {
                            AutorId = 3,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Stephen King"
                        },
                        new
                        {
                            AutorId = 4,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Isabel Allende"
                        },
                        new
                        {
                            AutorId = 5,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Haruki Murakami"
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Novela"
                        },
                        new
                        {
                            CategoriaId = 2,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            CategoriaId = 3,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Terror"
                        },
                        new
                        {
                            CategoriaId = 4,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            CategoriaId = 5,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Historia"
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            Email = "ana.garcia@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana García"
                        },
                        new
                        {
                            EstudianteId = 2,
                            Email = "pedro.martinez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro Martínez"
                        },
                        new
                        {
                            EstudianteId = 3,
                            Email = "maria.lopez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María López"
                        },
                        new
                        {
                            EstudianteId = 4,
                            Email = "carlos.rodriguez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            EstudianteId = 5,
                            Email = "laura.fernandez@email.com",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInscripcion = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura Fernández"
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("LibroId");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.HasIndex("UbicacionId");

                    b.ToTable("Libros", t =>
                        {
                            t.HasCheckConstraint("CK_Libro_ISBN", "LEN([ISBN]) >= 10 AND LEN([ISBN]) <= 13");
                        });

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307474728",
                            Serial = "9780307474728-1",
                            Titulo = "Cien años de soledad",
                            UbicacionId = 1
                        },
                        new
                        {
                            LibroId = 2,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "9788478884452-1",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 5
                        },
                        new
                        {
                            LibroId = 3,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788497593793",
                            Serial = "9788497593793-1",
                            Titulo = "El resplandor",
                            UbicacionId = 8
                        },
                        new
                        {
                            LibroId = 4,
                            AutorId = 4,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780525433477",
                            Serial = "9780525433477-1",
                            Titulo = "La casa de los espíritus",
                            UbicacionId = 2
                        },
                        new
                        {
                            LibroId = 5,
                            AutorId = 5,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788483835043",
                            Serial = "9788483835043-1",
                            Titulo = "Tokio blues",
                            UbicacionId = 3
                        },
                        new
                        {
                            LibroId = 6,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307387264",
                            Serial = "9780307387264-1",
                            Titulo = "El amor en los tiempos del cólera",
                            UbicacionId = 4
                        },
                        new
                        {
                            LibroId = 7,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884957",
                            Serial = "9788478884957-1",
                            Titulo = "Harry Potter y la cámara secreta",
                            UbicacionId = 6
                        },
                        new
                        {
                            LibroId = 8,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9781501142970",
                            Serial = "9781501142970-1",
                            Titulo = "It",
                            UbicacionId = 9
                        },
                        new
                        {
                            LibroId = 9,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307474728",
                            Serial = "9780307474728-2",
                            Titulo = "Cien años de soledad",
                            UbicacionId = 10
                        },
                        new
                        {
                            LibroId = 10,
                            AutorId = 1,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780307474728",
                            Serial = "9780307474728-3",
                            Titulo = "Cien años de soledad",
                            UbicacionId = 11
                        },
                        new
                        {
                            LibroId = 11,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "9788478884452-2",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 12
                        },
                        new
                        {
                            LibroId = 12,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "9788478884452-3",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 13
                        },
                        new
                        {
                            LibroId = 13,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884452",
                            Serial = "9788478884452-4",
                            Titulo = "Harry Potter y la piedra filosofal",
                            UbicacionId = 5
                        },
                        new
                        {
                            LibroId = 14,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788497593793",
                            Serial = "9788497593793-2",
                            Titulo = "El resplandor",
                            UbicacionId = 14
                        },
                        new
                        {
                            LibroId = 15,
                            AutorId = 4,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780525433477",
                            Serial = "9780525433477-2",
                            Titulo = "La casa de los espíritus",
                            UbicacionId = 15
                        },
                        new
                        {
                            LibroId = 16,
                            AutorId = 4,
                            CategoriaId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9780525433477",
                            Serial = "9780525433477-3",
                            Titulo = "La casa de los espíritus",
                            UbicacionId = 2
                        },
                        new
                        {
                            LibroId = 17,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884957",
                            Serial = "9788478884957-2",
                            Titulo = "Harry Potter y la cámara secreta",
                            UbicacionId = 6
                        },
                        new
                        {
                            LibroId = 18,
                            AutorId = 2,
                            CategoriaId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9788478884957",
                            Serial = "9788478884957-3",
                            Titulo = "Harry Potter y la cámara secreta",
                            UbicacionId = 7
                        },
                        new
                        {
                            LibroId = 19,
                            AutorId = 3,
                            CategoriaId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "9781501142970",
                            Serial = "9781501142970-2",
                            Titulo = "It",
                            UbicacionId = 9
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("LibroId", "EstudianteId", "FechaPrestamo")
                        .IsUnique();

                    b.ToTable("Prestamos", t =>
                        {
                            t.HasCheckConstraint("CK_Prestamo_FechaVencimiento", "[FechaVencimiento] > [FechaPrestamo]");
                        });

                    b.HasData(
                        new
                        {
                            PrestamoId = 1,
                            Estado = 1,
                            EstudianteId = 1,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDevolucion = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 1
                        },
                        new
                        {
                            PrestamoId = 2,
                            Estado = 2,
                            EstudianteId = 2,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 2
                        },
                        new
                        {
                            PrestamoId = 3,
                            Estado = 1,
                            EstudianteId = 3,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDevolucion = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 3
                        },
                        new
                        {
                            PrestamoId = 4,
                            Estado = 0,
                            EstudianteId = 4,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 4
                        });
                });

            modelBuilder.Entity("LibroManager.Models.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionId"));

                    b.Property<string>("Estante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.HasKey("UbicacionId");

                    b.ToTable("Ubicaciones");

                    b.HasData(
                        new
                        {
                            UbicacionId = 1,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 2,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 3,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 4,
                            Estante = "A",
                            Nivel = 1,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 5,
                            Estante = "A",
                            Nivel = 2,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 6,
                            Estante = "A",
                            Nivel = 2,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 7,
                            Estante = "A",
                            Nivel = 2,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 8,
                            Estante = "A",
                            Nivel = 2,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 9,
                            Estante = "A",
                            Nivel = 3,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 10,
                            Estante = "A",
                            Nivel = 3,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 11,
                            Estante = "A",
                            Nivel = 3,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 12,
                            Estante = "A",
                            Nivel = 3,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 13,
                            Estante = "B",
                            Nivel = 1,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 14,
                            Estante = "B",
                            Nivel = 1,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 15,
                            Estante = "B",
                            Nivel = 1,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 16,
                            Estante = "B",
                            Nivel = 1,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 17,
                            Estante = "B",
                            Nivel = 2,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 18,
                            Estante = "B",
                            Nivel = 2,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 19,
                            Estante = "B",
                            Nivel = 2,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 20,
                            Estante = "B",
                            Nivel = 2,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 21,
                            Estante = "B",
                            Nivel = 3,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 22,
                            Estante = "B",
                            Nivel = 3,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 23,
                            Estante = "B",
                            Nivel = 3,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 24,
                            Estante = "B",
                            Nivel = 3,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 25,
                            Estante = "C",
                            Nivel = 1,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 26,
                            Estante = "C",
                            Nivel = 1,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 27,
                            Estante = "C",
                            Nivel = 1,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 28,
                            Estante = "C",
                            Nivel = 1,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 29,
                            Estante = "C",
                            Nivel = 2,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 30,
                            Estante = "C",
                            Nivel = 2,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 31,
                            Estante = "C",
                            Nivel = 2,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 32,
                            Estante = "C",
                            Nivel = 2,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 33,
                            Estante = "C",
                            Nivel = 3,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 34,
                            Estante = "C",
                            Nivel = 3,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 35,
                            Estante = "C",
                            Nivel = 3,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 36,
                            Estante = "C",
                            Nivel = 3,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 37,
                            Estante = "D",
                            Nivel = 1,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 38,
                            Estante = "D",
                            Nivel = 1,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 39,
                            Estante = "D",
                            Nivel = 1,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 40,
                            Estante = "D",
                            Nivel = 1,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 41,
                            Estante = "D",
                            Nivel = 2,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 42,
                            Estante = "D",
                            Nivel = 2,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 43,
                            Estante = "D",
                            Nivel = 2,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 44,
                            Estante = "D",
                            Nivel = 2,
                            Posicion = 4
                        },
                        new
                        {
                            UbicacionId = 45,
                            Estante = "D",
                            Nivel = 3,
                            Posicion = 1
                        },
                        new
                        {
                            UbicacionId = 46,
                            Estante = "D",
                            Nivel = 3,
                            Posicion = 2
                        },
                        new
                        {
                            UbicacionId = 47,
                            Estante = "D",
                            Nivel = 3,
                            Posicion = 3
                        },
                        new
                        {
                            UbicacionId = 48,
                            Estante = "D",
                            Nivel = 3,
                            Posicion = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibroManager.Models.Libro", b =>
                {
                    b.HasOne("LibroManager.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibroManager.Models.Categoria", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibroManager.Models.Ubicacion", "Ubicacion")
                        .WithMany("Libros")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("LibroManager.Models.Prestamo", b =>
                {
                    b.HasOne("LibroManager.Models.Estudiante", "Estudiante")
                        .WithMany("Prestamos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibroManager.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LibroManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LibroManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibroManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LibroManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibroManager.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("LibroManager.Models.Categoria", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("LibroManager.Models.Estudiante", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("LibroManager.Models.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("LibroManager.Models.Ubicacion", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
