name: CI

on:
  push:
    branches: [ "main", "Testing" ]
  pull_request:
    branches: [ "main", "Testing" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
        working-directory: LibroManager
      - name: Build
        run: dotnet build --no-restore
        working-directory: LibroManager
      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI
      - name: Install Playwright Browsers
        run: playwright install
        working-directory: LibroManager.Tests.E2E
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: LibroManager
      - name: Upload Playwright Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            LibroManager.Tests.E2E/**/Diff/*.png
            LibroManager.Tests.E2E/**/Actual/*.png
            LibroManager.Tests.E2E/**/Golden/*.png
            LibroManager.Tests.E2E/Reports/*
